name: azkagram
description: Telegram Client unofficial menggunakan tdlib + bahasa code dart dan framework flutter.
repository: https://github.com/azkadev/azkagram
issue_tracker: https://github.com/azkadev/azkagram
publish_to: "none"
version: 0.0.0

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  path_provider: ^2.0.11
  hive_flutter: ^1.1.0
  zxing2: ^0.1.0
  image: ^3.2.2
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  cool_alert: ^1.1.0
  hexaminate: ^0.1.4
  telegram_client: ^0.3.71
  galaxeus_lib: ^0.0.27
  pretty_qr_code: ^2.0.2
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  simulate: ^0.0.12

flutter:
  uses-material-design: true

  assets:
    - assets/debug/
    - assets/icons/
    - assets/sound/
